# Web Scraping on Formula1 website

In [2]:
# Import libraries

from bs4 import BeautifulSoup
import urllib.request  # handle and fetches specified urls and gets info from the site
import html5lib
from functools import wraps
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# To get the race result for the Mexico Grand Prix held October

source = urllib.request.urlopen('https://www.formula1.com/en/results.html/2023/races/1223/mexico/race-result.html').read()
soup = BeautifulSoup(source, 'lxml')
table = soup.find_all('table', )[0]
race_result = pd.read_html(str(table), header= [0])[0]
race_result.head()

,Unnamed: 0,Pos,No,Driver,Car,Laps,Time/Retired,PTS,Unnamed: 8
0,NaN,1,1,Max Verstappen VER,Red Bull Racing Honda RBPT,71,2:02:30.814,25,NaN
1,NaN,2,44,Lewis Hamilton HAM,Mercedes,71,+13.875s,19,NaN
2,NaN,3,16,Charles Leclerc LEC,Ferrari,71,+23.124s,15,NaN
3,NaN,4,55,Carlos Sainz SAI,Ferrari,71,+27.154s,12,NaN
4,NaN,5,4,Lando Norris NOR,McLaren Mercedes,71,+33.266s,10,NaN

In [4]:
# Drop unwanted columns and rename columns

race_result.drop(["Unnamed: 0", "Unnamed: 8"], axis=1, inplace=True)
race_result.rename(columns={"Pos":"Position", "PTS":"Points", "Car":"Team"}, inplace=True)
race_result.head

<bound method NDFrame.head of    Position  No                Driver                          Team  Laps  \
0         1   1    Max Verstappen VER    Red Bull Racing Honda RBPT    71
1         2  44    Lewis Hamilton HAM                      Mercedes    71
2         3  16   Charles Leclerc LEC                       Ferrari    71
3         4  55      Carlos Sainz SAI                       Ferrari    71
4         5   4      Lando Norris NOR              McLaren Mercedes    71
5         6  63    George Russell RUS                      Mercedes    71
6         7   3  Daniel Ricciardo RIC         AlphaTauri Honda RBPT    71
7         8  81     Oscar Piastri PIA              McLaren Mercedes    71
8         9  23   Alexander Albon ALB             Williams Mercedes    71
9        10  31      Esteban Ocon OCO                Alpine Renault    71
10       11  10      Pierre Gasly GAS                Alpine Renault    71
11       12  22      Yuki Tsunoda TSU         AlphaTauri Honda RBPT    71
12       13  27   Nico Hulkenberg HUL                  Haas Ferrari    71
13       14  24       Zhou Guanyu ZHO            Alfa Romeo Ferrari    71
14       15  77   Valtteri Bottas BOT            Alfa Romeo Ferrari    71
15       16   2    Logan Sargeant SAR             Williams Mercedes    70
16       17  18      Lance Stroll STR  Aston Martin Aramco Mercedes    66
17       NC  14   Fernando Alonso ALO  Aston Martin Aramco Mercedes    47
18       NC  20   Kevin Magnussen MAG                  Haas Ferrari    31
19       NC  11      Sergio Perez PER    Red Bull Racing Honda RBPT     1

   Time/Retired  Points
0   2:02:30.814      25
1      +13.875s      19
2      +23.124s      15
3      +27.154s      12
4      +33.266s      10
5      +41.020s       8
6      +41.570s       6
7      +43.104s       4
8      +48.573s       2
9      +62.879s       1
10     +66.208s       0
11     +78.982s       0
12     +80.309s       0
13     +81.676s       0
14     +85.597s       0
15          DNF       0
16          DNF       0
17          DNF       0
18          DNF       0
19          DNF       0  >

In [5]:
# Get the result of the fastest lap of the grand prix

source = urllib.request.urlopen("https://www.formula1.com/en/results.html/2023/races/1223/mexico/fastest-laps.html").read()
soup = BeautifulSoup(source, 'lxml')
table = soup.find_all('table', )[0]
fastlestlap = pd.read_html(str(table), header= [0])[0]
fastlestlap.head()

,Unnamed: 0,Pos,No,Driver,Car,Lap,Time of day,Time,Avg Speed,Unnamed: 9
0,NaN,1,44,Lewis Hamilton HAM,Mercedes,71,16:06:02,1:21.334,190.503,NaN
1,NaN,2,1,Max Verstappen VER,Red Bull Racing Honda RBPT,40,15:23:19,1:21.644,189.780,NaN
2,NaN,3,4,Lando Norris NOR,McLaren Mercedes,71,16:06:22,1:21.944,189.085,NaN
3,NaN,4,16,Charles Leclerc LEC,Ferrari,38,15:20:37,1:22.332,188.194,NaN
4,NaN,5,22,Yuki Tsunoda TSU,AlphaTauri Honda RBPT,11,14:19:49,1:22.501,187.808,NaN

In [6]:
# Drop unwanted columns and rename columns

fastlestlap.drop(["Unnamed: 0", "Unnamed: 9", "Time of day", "Lap", "Car","Driver"], axis=1, inplace=True)
fastlestlap.rename(columns={"Pos":"FastestLap_Position", "Time":"FastestLap_Time", "Avg Speed":"FastestLap_Avg_Speed"}, inplace=True)
fastlestlap.head

<bound method NDFrame.head of     FastestLap_Position  No FastestLap_Time  FastestLap_Avg_Speed
0                     1  44        1:21.334               190.503
1                     2   1        1:21.644               189.780
2                     3   4        1:21.944               189.085
3                     4  16        1:22.332               188.194
4                     5  22        1:22.501               187.808
5                     6  55        1:22.539               187.722
6                     7   3        1:22.679               187.404
7                     8  81        1:22.760               187.220
8                     9  23        1:22.773               187.191
9                    10  63        1:22.780               187.175
10                   11  31        1:22.976               186.733
11                   12   2        1:23.003               186.672
12                   13  20        1:23.146               186.351
13                   14  77        1:23.166               186.306
14                   15  27        1:23.222               186.181
15                   16  10        1:23.230               186.163
16                   17  18        1:23.257               186.103
17                   18  14        1:23.531               185.492
18                   19  24        1:23.567               185.412>

In [7]:
# Get 2023 drivers' standing information

source = urllib.request.urlopen('https://www.formula1.com/en/results.html/2023/drivers.html').read()
soup = BeautifulSoup(source, 'lxml')
table = soup.find_all('table', )[0]
drivers_standing = pd.read_html(str(table), header= [0])[0]
drivers_standing.head()

,Unnamed: 0,Pos,Driver,Nationality,Car,PTS,Unnamed: 6
0,NaN,1,Max Verstappen VER,NED,Red Bull Racing Honda RBPT,491,NaN
1,NaN,2,Sergio Perez PER,MEX,Red Bull Racing Honda RBPT,240,NaN
2,NaN,3,Lewis Hamilton HAM,GBR,Mercedes,220,NaN
3,NaN,4,Carlos Sainz SAI,ESP,Ferrari,183,NaN
4,NaN,5,Fernando Alonso ALO,ESP,Aston Martin Aramco Mercedes,183,NaN

In [8]:
# Drop unwanted columns and rename column

drivers_standing.drop(["Unnamed: 0", "Unnamed: 6", "Pos", "Car"], axis=1, inplace=True)
drivers_standing.rename(columns={"PTS":"Season_Points", "Nationality":"Drivers_Nationality"}, inplace=True)
drivers_standing.head()

                Driver Drivers_Nationality  Season_Points
0   Max Verstappen VER                 NED            491
1     Sergio Perez PER                 MEX            240
2   Lewis Hamilton HAM                 GBR            220
3     Carlos Sainz SAI                 ESP            183
4  Fernando Alonso ALO                 ESP            183

In [9]:
# Merge all the data

mexico = race_result.merge(fastlestlap, how ='left',on = ["No"])
mexico_gp = mexico.merge(drivers_standing, how ='left',on = ['Driver'])
mexico_gp

,Position,No,Driver,Team,Laps,Time/Retired,Points,FastestLap_Position,FastestLap_Time,FastestLap_Avg_Speed,Drivers_Nationality,Season_Points
0,1,1,Max Verstappen VER,Red Bull Racing Honda RBPT,71,2:02:30.814,25,2.0,1:21.644,189.780,NED,491
1,2,44,Lewis Hamilton HAM,Mercedes,71,+13.875s,19,1.0,1:21.334,190.503,GBR,220
2,3,16,Charles Leclerc LEC,Ferrari,71,+23.124s,15,4.0,1:22.332,188.194,MON,166
3,4,55,Carlos Sainz SAI,Ferrari,71,+27.154s,12,6.0,1:22.539,187.722,ESP,183
4,5,4,Lando Norris NOR,McLaren Mercedes,71,+33.266s,10,3.0,1:21.944,189.085,GBR,169
5,6,63,George Russell RUS,Mercedes,71,+41.020s,8,10.0,1:22.780,187.175,GBR,151
6,7,3,Daniel Ricciardo RIC,AlphaTauri Honda RBPT,71,+41.570s,6,7.0,1:22.679,187.404,AUS,6
7,8,81,Oscar Piastri PIA,McLaren Mercedes,71,+43.104s,4,8.0,1:22.760,187.220,AUS,87
8,9,23,Alexander Albon ALB,Williams Mercedes,71,+48.573s,2,9.0,1:22.773,187.191,THA,27
9,10,31,Esteban Ocon OCO,Alpine Renault,71,+62.879s,1,11.0,1:22.976,186.733,FRA,45
10,11,10,Pierre Gasly GAS,Alpine Renault,71,+66.208s,0,16.0,1:23.230,186.163,FRA,56
11,12,22,Yuki Tsunoda TSU,AlphaTauri Honda RBPT,71,+78.982s,0,5.0,1:22.501,187.808,JPN,8
12,13,27,Nico Hulkenberg HUL,Haas Ferrari,71,+80.309s,0,15.0,1:23.222,186.181,GER,9
13,14,24,Zhou Guanyu ZHO,Alfa Romeo Ferrari,71,+81.676s,0,19.0,1:23.567,185.412,CHN,6
14,15,77,Valtteri Bottas BOT,Alfa Romeo Ferrari,71,+85.597s,0,14.0,1:23.166,186.306,FIN,10
15,16,2,Logan Sargeant SAR,Williams Mercedes,70,DNF,0,12.0,1:23.003,186.672,USA,1
16,17,18,Lance Stroll STR,Aston Martin Aramco Mercedes,66,DNF,0,17.0,1:23.257,186.103,CAN,53
17,NC,14,Fernando Alonso ALO,Aston Martin Aramco Mercedes,47,DNF,0,18.0,1:23.531,185.492,ESP,183
18,NC,20,Kevin Magnussen MAG,Haas Ferrari,31,DNF,0,13.0,1:23.146,186.351,DEN,3
19,NC,11,Sergio Perez PER,Red Bull Racing Honda RBPT,1,DNF,0,NaN,NaN,NaN,MEX,240

In [11]:
# Save the data in csv format

mexico_gp.to_csv("mexico_gp.csv", index= False)

In [12]:
# Load the data

df = pd.read_csv("mexico_gp.csv")
df

,Position,No,Driver,Team,Laps,Time/Retired,Points,FastestLap_Position,FastestLap_Time,FastestLap_Avg_Speed,Drivers_Nationality,Season_Points
0,1,1,Max Verstappen VER,Red Bull Racing Honda RBPT,71,2:02:30.814,25,2.0,1:21.644,189.780,NED,491
1,2,44,Lewis Hamilton HAM,Mercedes,71,+13.875s,19,1.0,1:21.334,190.503,GBR,220
2,3,16,Charles Leclerc LEC,Ferrari,71,+23.124s,15,4.0,1:22.332,188.194,MON,166
3,4,55,Carlos Sainz SAI,Ferrari,71,+27.154s,12,6.0,1:22.539,187.722,ESP,183
4,5,4,Lando Norris NOR,McLaren Mercedes,71,+33.266s,10,3.0,1:21.944,189.085,GBR,169
5,6,63,George Russell RUS,Mercedes,71,+41.020s,8,10.0,1:22.780,187.175,GBR,151
6,7,3,Daniel Ricciardo RIC,AlphaTauri Honda RBPT,71,+41.570s,6,7.0,1:22.679,187.404,AUS,6
7,8,81,Oscar Piastri PIA,McLaren Mercedes,71,+43.104s,4,8.0,1:22.760,187.220,AUS,87
8,9,23,Alexander Albon ALB,Williams Mercedes,71,+48.573s,2,9.0,1:22.773,187.191,THA,27
9,10,31,Esteban Ocon OCO,Alpine Renault,71,+62.879s,1,11.0,1:22.976,186.733,FRA,45
10,11,10,Pierre Gasly GAS,Alpine Renault,71,+66.208s,0,16.0,1:23.230,186.163,FRA,56
11,12,22,Yuki Tsunoda TSU,AlphaTauri Honda RBPT,71,+78.982s,0,5.0,1:22.501,187.808,JPN,8
12,13,27,Nico Hulkenberg HUL,Haas Ferrari,71,+80.309s,0,15.0,1:23.222,186.181,GER,9
13,14,24,Zhou Guanyu ZHO,Alfa Romeo Ferrari,71,+81.676s,0,19.0,1:23.567,185.412,CHN,6
14,15,77,Valtteri Bottas BOT,Alfa Romeo Ferrari,71,+85.597s,0,14.0,1:23.166,186.306,FIN,10
15,16,2,Logan Sargeant SAR,Williams Mercedes,70,DNF,0,12.0,1:23.003,186.672,USA,1
16,17,18,Lance Stroll STR,Aston Martin Aramco Mercedes,66,DNF,0,17.0,1:23.257,186.103,CAN,53
17,NC,14,Fernando Alonso ALO,Aston Martin Aramco Mercedes,47,DNF,0,18.0,1:23.531,185.492,ESP,183
18,NC,20,Kevin Magnussen MAG,Haas Ferrari,31,DNF,0,13.0,1:23.146,186.351,DEN,3
19,NC,11,Sergio Perez PER,Red Bull Racing Honda RBPT,1,DNF,0,NaN,NaN,NaN,MEX,240

In [13]:
# Remove the last 3 letters from the 'Driver' column

df['Driver'] = df['Driver'].str[:-3]
df

,Position,No,Driver,Team,Laps,Time/Retired,Points,FastestLap_Position,FastestLap_Time,FastestLap_Avg_Speed,Drivers_Nationality,Season_Points
0,1,1,Max Verstappen,Red Bull Racing Honda RBPT,71,2:02:30.814,25,2.0,1:21.644,189.780,NED,491
1,2,44,Lewis Hamilton,Mercedes,71,+13.875s,19,1.0,1:21.334,190.503,GBR,220
2,3,16,Charles Leclerc,Ferrari,71,+23.124s,15,4.0,1:22.332,188.194,MON,166
3,4,55,Carlos Sainz,Ferrari,71,+27.154s,12,6.0,1:22.539,187.722,ESP,183
4,5,4,Lando Norris,McLaren Mercedes,71,+33.266s,10,3.0,1:21.944,189.085,GBR,169
5,6,63,George Russell,Mercedes,71,+41.020s,8,10.0,1:22.780,187.175,GBR,151
6,7,3,Daniel Ricciardo,AlphaTauri Honda RBPT,71,+41.570s,6,7.0,1:22.679,187.404,AUS,6
7,8,81,Oscar Piastri,McLaren Mercedes,71,+43.104s,4,8.0,1:22.760,187.220,AUS,87
8,9,23,Alexander Albon,Williams Mercedes,71,+48.573s,2,9.0,1:22.773,187.191,THA,27
9,10,31,Esteban Ocon,Alpine Renault,71,+62.879s,1,11.0,1:22.976,186.733,FRA,45
10,11,10,Pierre Gasly,Alpine Renault,71,+66.208s,0,16.0,1:23.230,186.163,FRA,56
11,12,22,Yuki Tsunoda,AlphaTauri Honda RBPT,71,+78.982s,0,5.0,1:22.501,187.808,JPN,8
12,13,27,Nico Hulkenberg,Haas Ferrari,71,+80.309s,0,15.0,1:23.222,186.181,GER,9
13,14,24,Zhou Guanyu,Alfa Romeo Ferrari,71,+81.676s,0,19.0,1:23.567,185.412,CHN,6
14,15,77,Valtteri Bottas,Alfa Romeo Ferrari,71,+85.597s,0,14.0,1:23.166,186.306,FIN,10
15,16,2,Logan Sargeant,Williams Mercedes,70,DNF,0,12.0,1:23.003,186.672,USA,1
16,17,18,Lance Stroll,Aston Martin Aramco Mercedes,66,DNF,0,17.0,1:23.257,186.103,CAN,53
17,NC,14,Fernando Alonso,Aston Martin Aramco Mercedes,47,DNF,0,18.0,1:23.531,185.492,ESP,183
18,NC,20,Kevin Magnussen,Haas Ferrari,31,DNF,0,13.0,1:23.146,186.351,DEN,3
19,NC,11,Sergio Perez,Red Bull Racing Honda RBPT,1,DNF,0,NaN,NaN,NaN,MEX,240

In [13]:
# Check the uniqueness of the car column

df.Team.unique()

array(['Red Bull Racing Honda RBPT', 'Mercedes', 'Ferrari',
       'McLaren Mercedes', 'AlphaTauri Honda RBPT', 'Williams Mercedes',
       'Alpine Renault', 'Haas Ferrari', 'Alfa Romeo Ferrari',
       'Aston Martin Aramco Mercedes'], dtype=object)

In [15]:
# 

df['Team'] = df['Team'].replace('Red Bull Racing Honda RBPT','Red Bull Racing')
df['Team'] = df['Team'].replace('McLaren Mercedes','McLaren')
df['Team'] = df['Team'].replace('AlphaTauri Honda RBPT','AlphaTauri')
df['Team'] = df['Team'].replace('Williams Mercedes','Williams')
df['Team'] = df['Team'].replace('Haas Ferrari','Haas')
df['Team'] = df['Team'].replace('Alfa Romeo Ferrari','Alfa Romeo')
df['Team'] = df['Team'].replace('Aston Martin Aramco Mercedes','Aston Martin')

df.Team.unique()

array(['Red Bull Racing', 'Mercedes', 'Ferrari', 'McLaren', 'AlphaTauri',
       'Williams', 'Alpine Renault', 'Haas', 'Alfa Romeo', 'Aston Martin'],
      dtype=object)

In [14]:
# Shows all the columns

df.columns

Index(['Position', 'No', 'Driver', 'Team', 'Laps', 'Time/Retired', 'Points',
       'FastestLap_Position', 'FastestLap_Time', 'FastestLap_Avg_Speed',
       'Drivers_Nationality', 'Season_Points'],
      dtype='object')

In [16]:
# check the uniqueness of the driver's nationality

df.Drivers_Nationality.unique()

array(['NED', 'GBR', 'MON', 'ESP', 'AUS', 'THA', 'FRA', 'JPN', 'GER',
       'CHN', 'FIN', 'USA', 'CAN', 'DEN', 'MEX'], dtype=object)

In [17]:
# Get the drivers'

df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('NED', 'Netherlands')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('GBR', 'Great Britain')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('MON', 'Monaco')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('ESP', 'Spain')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('AUS', 'Australia')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('THA', 'Thailand')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('FRA', 'France')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('JPN', 'Japan')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('GER', 'Germany')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('CHN', 'China')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('FIN', 'Finland')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('USA', 'United States')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('CAN', 'Canada')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('DEN', 'Denmark')
df['Drivers_Nationality'] = df['Drivers_Nationality'].replace('MEX', 'Mexico')

df.Drivers_Nationality.unique()

array(['Netherlands', 'Great Britain', 'Monaco', 'Spain', 'Australia',
       'Thailand', 'France', 'Japan', 'Germany', 'China', 'Finland',
       'United States', 'Canada', 'Denmark', 'Mexico'], dtype=object)

In [19]:
# Rearrange the coulmns

df = df[['Position', "No", "Driver", "Drivers_Nationality","Team", "Laps", "Time/Retired",
         "FastestLap_Position", "FastestLap_Time", "FastestLap_Avg_Speed", "Points", "Season_Points"]]

In [23]:
df.head(20)

,Position,No,Driver,Drivers_Nationality,Team,Laps,Time/Retired,FastestLap_Position,FastestLap_Time,FastestLap_Avg_Speed,Points,Season_Points
0,1,1,Max Verstappen,Netherlands,Red Bull Racing,71,2:02:30.814,2.0,1:21.644,189.780,25,491
1,2,44,Lewis Hamilton,Great Britain,Mercedes,71,+13.875s,1.0,1:21.334,190.503,19,220
2,3,16,Charles Leclerc,Monaco,Ferrari,71,+23.124s,4.0,1:22.332,188.194,15,166
3,4,55,Carlos Sainz,Spain,Ferrari,71,+27.154s,6.0,1:22.539,187.722,12,183
4,5,4,Lando Norris,Great Britain,McLaren,71,+33.266s,3.0,1:21.944,189.085,10,169
5,6,63,George Russell,Great Britain,Mercedes,71,+41.020s,10.0,1:22.780,187.175,8,151
6,7,3,Daniel Ricciardo,Australia,AlphaTauri,71,+41.570s,7.0,1:22.679,187.404,6,6
7,8,81,Oscar Piastri,Australia,McLaren,71,+43.104s,8.0,1:22.760,187.220,4,87
8,9,23,Alexander Albon,Thailand,Williams,71,+48.573s,9.0,1:22.773,187.191,2,27
9,10,31,Esteban Ocon,France,Alpine Renault,71,+62.879s,11.0,1:22.976,186.733,1,45
10,11,10,Pierre Gasly,France,Alpine Renault,71,+66.208s,16.0,1:23.230,186.163,0,56
11,12,22,Yuki Tsunoda,Japan,AlphaTauri,71,+78.982s,5.0,1:22.501,187.808,0,8
12,13,27,Nico Hulkenberg,Germany,Haas,71,+80.309s,15.0,1:23.222,186.181,0,9
13,14,24,Zhou Guanyu,China,Alfa Romeo,71,+81.676s,19.0,1:23.567,185.412,0,6
14,15,77,Valtteri Bottas,Finland,Alfa Romeo,71,+85.597s,14.0,1:23.166,186.306,0,10
15,16,2,Logan Sargeant,United States,Williams,70,DNF,12.0,1:23.003,186.672,0,1
16,17,18,Lance Stroll,Canada,Aston Martin,66,DNF,17.0,1:23.257,186.103,0,53
17,NC,14,Fernando Alonso,Spain,Aston Martin,47,DNF,18.0,1:23.531,185.492,0,183
18,NC,20,Kevin Magnussen,Denmark,Haas,31,DNF,13.0,1:23.146,186.351,0,3
19,NC,11,Sergio Perez,Mexico,Red Bull Racing,1,DNF,NaN,NaN,NaN,0,240

In [21]:
df.shape

(20, 12)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Position              20 non-null     object
 1   No                    20 non-null     int64
 2   Driver                20 non-null     object
 3   Drivers_Nationality   20 non-null     object
 4   Team                  20 non-null     object
 5   Laps                  20 non-null     int64
 6   Time/Retired          20 non-null     object
 7   FastestLap_Position   19 non-null     float64
 8   FastestLap_Time       19 non-null     object
 9   FastestLap_Avg_Speed  19 non-null     float64
 10  Points                20 non-null     int64
 11  Season_Points         20 non-null     int64
dtypes: float64(2), int64(4), object(6)
memory usage: 2.0+ KB

In [25]:
# Drop rows containing 'DNF' in the 'Time/Retired' column

df = df[df['Time/Retired'] != 'DNF']

# Print the updated DataFrame
print(df)

   Position  No             Driver Drivers_Nationality             Team  Laps  \
0         1   1    Max Verstappen          Netherlands  Red Bull Racing    71
1         2  44    Lewis Hamilton        Great Britain         Mercedes    71
2         3  16   Charles Leclerc               Monaco          Ferrari    71
3         4  55      Carlos Sainz                Spain          Ferrari    71
4         5   4      Lando Norris        Great Britain          McLaren    71
5         6  63    George Russell        Great Britain         Mercedes    71
6         7   3  Daniel Ricciardo            Australia       AlphaTauri    71
7         8  81     Oscar Piastri            Australia          McLaren    71
8         9  23   Alexander Albon             Thailand         Williams    71
9        10  31      Esteban Ocon               France   Alpine Renault    71
10       11  10      Pierre Gasly               France   Alpine Renault    71
11       12  22      Yuki Tsunoda                Japan       AlphaTauri    71
12       13  27   Nico Hulkenberg              Germany             Haas    71
13       14  24       Zhou Guanyu                China       Alfa Romeo    71
14       15  77   Valtteri Bottas              Finland       Alfa Romeo    71

   Time/Retired  FastestLap_Position FastestLap_Time  FastestLap_Avg_Speed  \
0   2:02:30.814                  2.0        1:21.644               189.780
1      +13.875s                  1.0        1:21.334               190.503
2      +23.124s                  4.0        1:22.332               188.194
3      +27.154s                  6.0        1:22.539               187.722
4      +33.266s                  3.0        1:21.944               189.085
5      +41.020s                 10.0        1:22.780               187.175
6      +41.570s                  7.0        1:22.679               187.404
7      +43.104s                  8.0        1:22.760               187.220
8      +48.573s                  9.0        1:22.773               187.191
9      +62.879s                 11.0        1:22.976               186.733
10     +66.208s                 16.0        1:23.230               186.163
11     +78.982s                  5.0        1:22.501               187.808
12     +80.309s                 15.0        1:23.222               186.181
13     +81.676s                 19.0        1:23.567               185.412
14     +85.597s                 14.0        1:23.166               186.306

    Points  Season_Points
0       25            491
1       19            220
2       15            166
3       12            183
4       10            169
5        8            151
6        6              6
7        4             87
8        2             27
9        1             45
10       0             56
11       0              8
12       0              9
13       0              6
14       0             10

In [32]:
# change datatype

df.Position = df.Position.astype(int)
df.Fastestlap_Position = df.FastestLap_Position.astype(int)
#df.FastestLap_Time = df.FastestLap_Time.astype(float)

df.dtypes

Position                  int32
No                        int64
Driver                   object
Drivers_Nationality      object
Team                     object
Laps                      int64
Time/Retired             object
FastestLap_Position     float64
FastestLap_Time          object
FastestLap_Avg_Speed    float64
Points                    int64
Season_Points             int64
dtype: object

In [33]:
# Save the data in csv format

df.to_csv(r'C:\Users\hp\Desktop\folder for data output\mexico_grandprix.csv', index= False)

In [35]:
# Save the data in csv format

df.to_csv("mexico_gp.csv", index= False)

In [3]:
# Gest 2023 Constructor Standing

source = urllib.request.urlopen("https://www.formula1.com/en/results.html/2023/team.html").read()
soup = BeautifulSoup(source, 'lxml')
table = soup.find_all('table', )[0]
constructors = pd.read_html(str(table), header= [0])[0]
constructors.head()

   Unnamed: 0  Pos                          Team  PTS  Unnamed: 4
0         NaN    1    Red Bull Racing Honda RBPT  731         NaN
1         NaN    2                      Mercedes  371         NaN
2         NaN    3                       Ferrari  349         NaN
3         NaN    4              McLaren Mercedes  256         NaN
4         NaN    5  Aston Martin Aramco Mercedes  236         NaN

In [4]:
# Drop unwanted columns and rename column

constructors.drop(["Unnamed: 0", "Unnamed: 4", "Pos"], axis=1, inplace=True)
constructors.rename(columns={"PTS":"Constructor_Points"}, inplace=True)
constructors.head(3)

                         Team  Constructor_Points
0  Red Bull Racing Honda RBPT                 731
1                    Mercedes                 371
2                     Ferrari                 349

In [7]:
# Save the data in csv format

constructors.to_csv(r'C:\Users\hp\Desktop\folder for data output\constructors.csv', index= False)

constructors.to_csv("constructors.csv", index= False)